package br.com.gabriel.sysagendasrv.domain;
// Generated 18 de mar. de 2023 17:26:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name = "CONTATO")
public class Contato implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int codContato;
	private String nome;
	private Long telefone;

	public Contato() {
	}

	public Contato(int codContato) {
		this.codContato = codContato;
	}

	public Contato(int codContato, String nome, Long telefone) {
		this.codContato = codContato;
		this.nome = nome;
		this.telefone = telefone;
	}

	@Id

	@Column(name = "COD_CONTATO", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCodContato() {
		return this.codContato;
	}

	public void setCodContato(int codContato) {
		this.codContato = codContato;
	}

	@Column(name = "NOME", length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "TELEFONE", precision = 11, scale = 0)
	public Long getTelefone() {
		return this.telefone;
	}

	public void setTelefone(Long telefone) {
		this.telefone = telefone;
	}

}
