package br.com.gabriel.sysagendasrv.domain;
// Generated 18 de mar. de 2023 17:26:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ligacao generated by hbm2java
 */
@Entity
@Table(name = "LIGACAO")
public class Ligacao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private LigacaoId id;
	private Date dataHora;
	private String observacao;

	public Ligacao() {
	}

	public Ligacao(LigacaoId id, Date dataHora) {
		this.id = id;
		this.dataHora = dataHora;
	}

	public Ligacao(LigacaoId id, Date dataHora, String observacao) {
		this.id = id;
		this.dataHora = dataHora;
		this.observacao = observacao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codContato", column = @Column(name = "COD_CONTATO", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "codLigacao", column = @Column(name = "COD_LIGACAO", nullable = false, precision = 6, scale = 0)) })
	public LigacaoId getId() {
		return this.id;
	}

	public void setId(LigacaoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_HORA", nullable = false, length = 7)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

	@Column(name = "OBSERVACAO", length = 1000)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

}
